### ISSUE TITLE
http2下，通过edp-webserver代理会导致crash

### ISSUE THREAD

**Issue by PengXing** [ecomfe/edp-webserver#48]
```
Error: Cannot set deprecated header: connection
    at OutgoingResponse.setHeader (/usr/local/lib/node_modules/edp-webserver/node_modules/http2/lib/http.js:367:13)
    at OutgoingResponse.writeHead (/usr/local/lib/node_modules/edp-webserver/node_modules/http2/lib/http.js:716:10)
    at /usr/local/lib/node_modules/edp-webserver/lib/resource.js:52:34
    at Gzip.onEnd (zlib.js:227:5)
    at Gzip.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by PengXing** [comment]
在`http2`协议下，过滤掉proxy返回的一些`deprecated headers`
